### ISSUE TITLE
Role 3 : setting up Django website

### ISSUE THREAD

**Issue by RavidYael** [redhat-beyond/Beyond-07-team-3#4]
setting up the Pipnev
providing local http acccess to the vm
bootstraping a basic django website

**Comment by kobihk** [comment]
@RavidYael usually the issue opened before the PR is created
so you don't need to add the latest line in the Issue description.
in any way, you will see the linkage when you"ll add the link in the PR description like:
[RavidYael](https://github.com/RavidYael) mentioned this issue [1 hour ago]
https://github.com/redhat-beyond/Beyond-07-team-3/pull/3

Please delete the latest line from the issue description
